import { Product, Category, Seller, Order, Coupon, Review } from '@/types/marketplace';

export const CATEGORIES: Category[] = [
  {
    id: 'cat-electronics',
    name: 'Electronics',
    slug: 'electronics',
    iconName: 'Headphones',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=80',
    productCount: 48,
    description: 'Audio, wearables, smart home, and mobile accessories.'
  },
  {
    id: 'cat-fashion',
    name: 'Fashion',
    slug: 'fashion',
    iconName: 'Shirt',
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=500&auto=format&fit=crop&q=80',
    productCount: 124,
    description: 'Apparel, outerwear, everyday essentials, and footwear.'
  },
  {
    id: 'cat-home',
    name: 'Home & Living',
    slug: 'home-living',
    iconName: 'Armchair',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&auto=format&fit=crop&q=80',
    productCount: 86,
    description: 'Minimalist decor, furniture, candles, and kitchenware.'
  },
  {
    id: 'cat-beauty',
    name: 'Beauty',
    slug: 'beauty',
    iconName: 'Sparkles',
    imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=500&auto=format&fit=crop&q=80',
    productCount: 65,
    description: 'Clean skincare, botanical cosmetics, and self-care.'
  },
  {
    id: 'cat-baby',
    name: 'Baby & Kids',
    slug: 'baby-kids',
    iconName: 'Baby',
    imageUrl: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    productCount: 42,
    description: 'Eco-friendly wooden toys, nursery gear, and apparel.'
  },
  {
    id: 'cat-sports',
    name: 'Sports',
    slug: 'sports',
    iconName: 'Dumbbell',
    imageUrl: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=500&auto=format&fit=crop&q=80',
    productCount: 39,
    description: 'Fitness gear, weights, yoga mats, and active lifestyle.'
  },
  {
    id: 'cat-books',
    name: 'Books',
    slug: 'books',
    iconName: 'BookOpen',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500&auto=format&fit=crop&q=80',
    productCount: 57,
    description: 'Independent press, design monographs, and journals.'
  },
  {
    id: 'cat-groceries',
    name: 'Groceries',
    slug: 'groceries',
    iconName: 'Apple',
    imageUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=500&auto=format&fit=crop&q=80',
    productCount: 73,
    description: 'Artisanal roasts, organic pantry, and farm-fresh staples.'
  }
];

export const SELLERS: Seller[] = [
  {
    id: 'seller-1',
    storeName: 'Urban Thread Studio',
    slug: 'urban-thread',
    tagline: 'Refined modern essentials & sustainable textiles',
    description: 'An independent design atelier crafting high-quality everyday outerwear, structured hoodies, and premium breathable knits.',
    category: 'Fashion',
    rating: 4.9,
    reviewCount: 342,
    followersCount: 4890,
    productCount: 28,
    salesCount: 1420,
    location: 'Portland, OR',
    joinedDate: 'Jan 2025',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&auto=format&fit=crop&q=80',
    isVerified: true,
    isFeatured: true,
    status: 'active',
    commissionRate: 8,
    contactEmail: 'hello@urbanthread.co',
    phone: '+1 (503) 555-0192'
  },
  {
    id: 'seller-2',
    storeName: 'Casa Living Objects',
    slug: 'casa-living',
    tagline: 'Artisanal homeware & ambient ceramic craftsmanship',
    description: 'Hand-poured mineral candles, minimalist stoneware, and warm tactile living room centerpieces designed for slow living.',
    category: 'Home & Living',
    rating: 4.8,
    reviewCount: 278,
    followersCount: 3620,
    productCount: 34,
    salesCount: 980,
    location: 'Austin, TX',
    joinedDate: 'Mar 2025',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&auto=format&fit=crop&q=80',
    isVerified: true,
    isFeatured: true,
    status: 'active',
    commissionRate: 7.5,
    contactEmail: 'contact@casaliving.design',
    phone: '+1 (512) 555-0144'
  },
  {
    id: 'seller-3',
    storeName: 'TechNest Labs',
    slug: 'technest',
    tagline: 'Ergonomic personal audio & intelligent smart gear',
    description: 'Precision-engineered wireless audio drivers, ultra-light chronometers, and tactile desk tech for modern makers.',
    category: 'Electronics',
    rating: 4.9,
    reviewCount: 890,
    followersCount: 8400,
    productCount: 19,
    salesCount: 3120,
    location: 'San Jose, CA',
    joinedDate: 'Nov 2024',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&auto=format&fit=crop&q=80',
    isVerified: true,
    isFeatured: true,
    status: 'active',
    commissionRate: 9,
    contactEmail: 'support@technestlabs.io',
    phone: '+1 (408) 555-0188'
  },
  {
    id: 'seller-4',
    storeName: 'Glow & Co. Botanicals',
    slug: 'glow-and-co',
    tagline: 'Pure plant-active formulations & radiant rituals',
    description: 'Small-batch cold-pressed face elixirs, soothing peptide moisturizers, and clean beauty sets formulated in California.',
    category: 'Beauty',
    rating: 4.9,
    reviewCount: 412,
    followersCount: 5210,
    productCount: 22,
    salesCount: 1850,
    location: 'Santa Barbara, CA',
    joinedDate: 'Feb 2025',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=1200&auto=format&fit=crop&q=80',
    isVerified: true,
    isFeatured: true,
    status: 'active',
    commissionRate: 8,
    contactEmail: 'care@glowandco.bio',
    phone: '+1 (805) 555-0163'
  },
  {
    id: 'seller-5',
    storeName: 'Daily Harvest Provisions',
    slug: 'daily-harvest',
    tagline: 'Single-origin beans, raw organic honeys & pantry luxuries',
    description: 'Direct trade coffee beans roasted weekly, cold-extracted wildflower honeys, and handcrafted small-batch pantry provisions.',
    category: 'Groceries',
    rating: 4.8,
    reviewCount: 195,
    followersCount: 2900,
    productCount: 31,
    salesCount: 840,
    location: 'Seattle, WA',
    joinedDate: 'Apr 2025',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=1200&auto=format&fit=crop&q=80',
    isVerified: true,
    isFeatured: false,
    status: 'active',
    commissionRate: 7,
    contactEmail: 'pantry@dailyharvest.market',
    phone: '+1 (206) 555-0177'
  },
  {
    id: 'seller-6',
    storeName: 'Little Sprout Studio',
    slug: 'little-sprout',
    tagline: 'Montessori wooden toys & organic nursery essentials',
    description: 'Sustainably harvested non-toxic baby essentials, stacking rings, balance boards, and feather-light travel strollers.',
    category: 'Baby & Kids',
    rating: 4.9,
    reviewCount: 310,
    followersCount: 4120,
    productCount: 24,
    salesCount: 1100,
    location: 'Boulder, CO',
    joinedDate: 'May 2025',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=1200&auto=format&fit=crop&q=80',
    isVerified: true,
    isFeatured: false,
    status: 'active',
    commissionRate: 8,
    contactEmail: 'team@littlesprout.shop',
    phone: '+1 (303) 555-0129'
  }
];

export const PRODUCTS: Product[] = [
  // Trending 1: Wireless Earbuds Pro
  {
    id: 'prod-earbuds-pro',
    name: 'Wireless Earbuds Pro with Spatial Audio',
    category: 'Electronics',
    price: 2499,
    originalPrice: 3800,
    discountPercent: 34,
    rating: 4.8,
    reviewCount: 1240,
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?w=600&auto=format&fit=crop&q=80'
    ],
    sellerId: 'seller-3',
    sellerName: 'TechNest Labs',
    sellerRating: 4.9,
    sellerLocation: 'San Jose, CA',
    isTrending: true,
    isDeal: true,
    inStock: true,
    stockCount: 84,
    supplierPrice: 1600,
    suggestedPrice: 2499,
    resellerProfit: 899,
    isActive: true,
    description: 'Engineered with custom beryllium acoustic drivers and active noise cancellation. Features seamless instant Bluetooth 5.3 pairing, transparent awareness mode, and 36 hours of total wireless playtime with wireless charging case.',
    features: [
      'Active Noise Cancellation up to 35dB',
      'Lossless Hi-Fi low-latency codec',
      'IPX5 water & sweat resistant',
      '8 hours single charge / 36 hours with capsule case'
    ],
    specifications: {
      'Driver Size': '11mm Dynamic Drivers',
      'Connectivity': 'Bluetooth 5.3',
      'Battery Life': '36 Hours total',
      'Weight': '4.2g per earbud'
    },
    brand: 'TechNest Labs',
    sku: 'TN-EAR-PRO-01',
    bulkPricingEnabled: true,
    bulkPricingTiers: [
      { minQuantity: 5, unitPrice: 2299, discountPercent: 8 },
      { minQuantity: 10, unitPrice: 2099, discountPercent: 16 },
      { minQuantity: 25, unitPrice: 1899, discountPercent: 24 }
    ],
    colors: ['Silver Chrome', 'Matte Obsidian', 'Alabaster White'],
    createdAt: '2026-01-10'
  },
  // Trending 2: Minimalist Weatherproof Jacket
  {
    id: 'prod-minimalist-backpack',
    name: 'Minimalist Weatherproof Jacket',
    category: 'Fashion',
    price: 3200,
    originalPrice: 5400,
    discountPercent: 41,
    rating: 4.9,
    reviewCount: 845,
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1544441893-675973e31985?w=600&auto=format&fit=crop&q=80'
    ],
    sellerId: 'seller-1',
    sellerName: 'Urban Thread Studio',
    sellerRating: 4.9,
    sellerLocation: 'Portland, OR',
    brand: 'Urban Thread',
    sku: 'UT-JKT-COMM-02',
    bulkPricingEnabled: true,
    bulkPricingTiers: [
      { minQuantity: 5, unitPrice: 2850, discountPercent: 11 },
      { minQuantity: 10, unitPrice: 2550, discountPercent: 20 }
    ],
    isTrending: true,
    inStock: true,
    stockCount: 42,
    supplierPrice: 2100,
    suggestedPrice: 3200,
    resellerProfit: 1100,
    isActive: true,
    description: 'Designed for daily urban commuting and unpredictable weather. Crafted from waterproof breathable ripstop fabric with matte weather-repellent coating, taped seams, and hidden interior tech pockets.',
    features: [
      'Hydrophobic breathable membrane coating',
      'Waterproof seam-sealed YKK zips',
      'Adjustable storm hood & cinch cuffs',
      'Ultra-lightweight packable architecture'
    ],
    specifications: {
      'Material': 'Waterproof DWR Ripstop',
      'Weight': '420g',
      'Breathability': '10,000 g/m²',
      'Waterproof Rating': '15,000 mm'
    },
    colors: ['Matte Black', 'Olive Drab', 'Slate Grey'],
    sizes: ['S', 'M', 'L', 'XL'],
    createdAt: '2026-02-01'
  },
  // Trending 3: Scented Candle
  {
    id: 'prod-scented-candle',
    name: 'Artisan Sandalwood & Cedar Scented Candle',
    category: 'Home & Living',
    price: 850,
    originalPrice: 1300,
    discountPercent: 35,
    rating: 4.7,
    reviewCount: 632,
    imageUrl: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&auto=format&fit=crop&q=80',
    sellerId: 'seller-2',
    sellerName: 'Casa Living Objects',
    sellerRating: 4.8,
    sellerLocation: 'Austin, TX',
    brand: 'Casa Living',
    sku: 'CL-CNDL-SWD-03',
    bulkPricingEnabled: true,
    bulkPricingTiers: [
      { minQuantity: 4, unitPrice: 750, discountPercent: 12 },
      { minQuantity: 12, unitPrice: 650, discountPercent: 24 },
      { minQuantity: 24, unitPrice: 550, discountPercent: 35 }
    ],
    isTrending: true,
    inStock: true,
    stockCount: 3,
    isActive: false,
    description: 'Slow-poured using 100% natural soy wax infused with botanical essential oils of virgin cedarwood, warm amber, and smoked sandalwood. Clean-burning cotton wick delivers a rich, soothing atmosphere.',
    features: [
      '100% domestic non-GMO soy wax',
      '55-60 hours burn time',
      'Zero phthalates, parabens, or synthetic dyes',
      'Reusable matte ceramic vessel'
    ],
    specifications: {
      'Net Weight': '8.5 oz / 240g',
      'Burn Time': '55+ Hours',
      'Wick': 'Natural unbleached cotton',
      'Origin': 'Handmade in Austin, USA'
    },
    createdAt: '2026-02-15'
  },
  // Trending 4: Smart Watch Series 8
  {
    id: 'prod-smart-watch',
    name: 'Aero Chrono Smart Watch with AMOLED Display',
    category: 'Electronics',
    price: 6500,
    originalPrice: 9999,
    discountPercent: 35,
    rating: 4.9,
    reviewCount: 973,
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop&q=80'
    ],
    sellerId: 'seller-3',
    sellerName: 'TechNest Labs',
    sellerRating: 4.9,
    sellerLocation: 'San Jose, CA',
    isTrending: true,
    isDeal: true,
    inStock: true,
    stockCount: 38,
    isActive: false,
    description: 'Featuring an edge-to-edge sapphire crystal AMOLED display with always-on clarity. Tracks blood oxygen, 24/7 heart rate variability, sleep stages, and over 60 sports modes with 12 days of battery stamina.',
    features: [
      '1.43" Ultra-HD AMOLED Display (466x466)',
      '12-day battery on standard usage',
      'Built-in Dual-band GPS tracking',
      'Titanium aerospace bezel with magnetic strap'
    ],
    specifications: {
      'Display': '1.43-inch AMOLED Sapphire Glass',
      'Water Resistance': '5 ATM (50m depth)',
      'Sensors': 'Optical HR, SpO2, Accelerometer, Barometer',
      'Compatibility': 'iOS & Android'
    },
    colors: ['Midnight Titanium', 'Starlight Silver'],
    createdAt: '2026-01-20'
  },
  // Trending 5: Skincare Set
  {
    id: 'prod-skincare-set',
    name: 'Botanical Radiance 3-Piece Skincare Ritual',
    category: 'Beauty',
    price: 1850,
    originalPrice: 2800,
    discountPercent: 34,
    rating: 4.8,
    reviewCount: 1120,
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80',
    sellerId: 'seller-4',
    sellerName: 'Glow & Co. Botanicals',
    sellerRating: 4.9,
    sellerLocation: 'Santa Barbara, CA',
    isTrending: true,
    inStock: true,
    stockCount: 50,
    isActive: false,
    description: 'A complete daily regimen formulated with hyaluronic acid, cold-pressed rosehip seed oil, and plant squalane. Includes Gentle Hydrating Cleanser, Vitamin C Glow Elixir, and Barrier Restoring Moisturizer.',
    features: [
      'Clinically tested dermatologist formulated',
      'Dermatologically certified for sensitive skin',
      'Cruelty-free, vegan certified',
      'Eco-friendly recyclable amber glass packaging'
    ],
    specifications: {
      'Set Includes': 'Cleanser (100ml), Serum (30ml), Cream (50ml)',
      'Skin Type': 'All Skin Types',
      'Formulation': 'Clean Botanical Active'
    },
    createdAt: '2026-02-12'
  },

  // Recommended 1: Bluetooth Speaker
  {
    id: 'prod-bt-speaker',
    name: 'Studio Pulse 360 Waterproof Bluetooth Speaker',
    category: 'Electronics',
    price: 2800,
    originalPrice: 4800,
    discountPercent: 42,
    rating: 4.7,
    reviewCount: 450,
    imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80',
    sellerId: 'seller-3',
    sellerName: 'TechNest Labs',
    sellerRating: 4.9,
    sellerLocation: 'San Jose, CA',
    isRecommended: true,
    inStock: true,
    stockCount: 55,
    isActive: false,
    description: 'Compact acoustic marvel delivering immersive 360-degree sound with punchy bass radiators. IPX7 waterproof rating ensures worry-free listening poolside, at beach campsites, or in the shower.',
    features: [
      'Dual 15W full-range acoustic drivers',
      'IPX7 submersible waterproof design',
      '20 hours continuous audio playback',
      'TWS pairing to link two speakers for stereo'
    ],
    specifications: {
      'Power Output': '30W Peak',
      'Battery': '5200mAh Lithium-ion',
      'Weight': '540g'
    },
    colors: ['Charcoal Black', 'Ocean Blue', 'Warm Sand'],
    createdAt: '2026-01-25'
  },
  // Recommended 2: Oversized Hoodie
  {
    id: 'prod-oversized-hoodie',
    name: 'Heavyweight Brushed Organic Cotton Hoodie',
    category: 'Fashion',
    price: 2100,
    originalPrice: 3300,
    discountPercent: 36,
    rating: 4.9,
    reviewCount: 520,
    imageUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&auto=format&fit=crop&q=80',
    sellerId: 'seller-1',
    sellerName: 'Urban Thread Studio',
    sellerRating: 4.9,
    sellerLocation: 'Portland, OR',
    isRecommended: true,
    inStock: true,
    stockCount: 78,
    isActive: false,
    description: 'Cut in a relaxed dropped-shoulder silhouette from ultra-dense 460GSM combed organic fleece. Features double-lined hood without drawstrings for a clean architectural profile.',
    features: [
      '100% GOTS-certified Organic French Terry',
      'Heavyweight 460 GSM fabric',
      'Pre-shrunk garment dyed wash',
      'Ribbed side gussets for mobility'
    ],
    specifications: {
      'Fit': 'Relaxed / Dropped Shoulder',
      'Care': 'Machine wash cold, lay flat to dry',
      'Country of Origin': 'Made sustainably in Portugal'
    },
    colors: ['Heather Grey', 'Washed Black', 'Oatmeal Milk', 'Forest Sage'],
    sizes: ['S', 'M', 'L', 'XL'],
    createdAt: '2026-02-05'
  },
  // Recommended 3: Coffee Maker
  {
    id: 'prod-coffee-maker',
    name: 'Precision Drip Thermal Carafe Coffee Maker',
    category: 'Home & Living',
    price: 3600,
    originalPrice: 6200,
    discountPercent: 42,
    rating: 4.8,
    reviewCount: 680,
    imageUrl: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=600&auto=format&fit=crop&q=80',
    sellerId: 'seller-2',
    sellerName: 'Casa Living Objects',
    sellerRating: 4.8,
    sellerLocation: 'Austin, TX',
    isRecommended: true,
    isDeal: true,
    inStock: true,
    stockCount: 30,
    isActive: false,
    description: 'Golden Cup certified showerhead extracts optimal flavor nuance at the ideal 200°F brewing temperature. Double-wall vacuum stainless steel carafe preserves freshness without bitter heating plates.',
    features: [
      'Gold-tone reusable fine micro-mesh filter',
      '10-cup double-walled thermal carafe',
      'Programmable 24-hour automatic timer',
      'Removable wide-mouth water reservoir'
    ],
    specifications: {
      'Capacity': '1.25L / 10 Cups',
      'Wattage': '1200W High Speed Heating',
      'Carafe Material': '18/8 Stainless Steel'
    },
    createdAt: '2026-01-18'
  },
  // Recommended 4: Makeup Kit
  {
    id: 'prod-makeup-kit',
    name: 'Neutral Mineral Eyeshadow & Contour Palette',
    category: 'Beauty',
    price: 1400,
    originalPrice: 2400,
    discountPercent: 42,
    rating: 4.8,
    reviewCount: 390,
    imageUrl: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=600&auto=format&fit=crop&q=80',
    sellerId: 'seller-4',
    sellerName: 'Glow & Co. Botanicals',
    sellerRating: 4.9,
    sellerLocation: 'Santa Barbara, CA',
    isRecommended: true,
    inStock: true,
    stockCount: 60,
    isActive: false,
    description: 'Featuring 12 buttery transition shades spanning warm clays, soft taupes, champagne shimmers, and rich espresso. Formulated with mica and nourishing jojoba oil for seamless blendability.',
    features: [
      'Talc-free mineral pigment formula',
      '12 versatile matte and satin finishes',
      'Non-creasing 14-hour wear',
      'Integrated panoramic vanity mirror'
    ],
    specifications: {
      'Net Weight': '14.4g total',
      'Shelf Life': '24 Months after opening',
      'Cruelty Free': 'Yes'
    },
    createdAt: '2026-02-18'
  },
  // Recommended 5: Baby Stroller
  {
    id: 'prod-baby-stroller',
    name: 'Ultra-Compact Modular All-Terrain Baby Stroller',
    category: 'Baby & Kids',
    price: 8900,
    originalPrice: 14500,
    discountPercent: 39,
    rating: 4.9,
    reviewCount: 310,
    imageUrl: 'https://images.unsplash.com/photo-1591088398332-8a7791972843?w=600&auto=format&fit=crop&q=80',
    sellerId: 'seller-6',
    sellerName: 'Little Sprout Studio',
    sellerRating: 4.9,
    sellerLocation: 'Boulder, CO',
    isRecommended: true,
    inStock: true,
    stockCount: 4,
    isActive: false,
    description: 'Ultra-lightweight magnesium alloy chassis with one-hand instant folding mechanism. Fits in airplane overhead luggage bins while offering four-wheel spring suspension for cobblestones and parks.',
    features: [
      'One-hand gravity fold down in 1.5 seconds',
      'UPF 50+ extendable sunshade canopy',
      'Reclinable flat sleeper seat for newborns',
      'Weight: only 6.2 kg'
    ],
    specifications: {
      'Weight Limit': 'Up to 22kg (Newborn to 4 years)',
      'Dimensions Folded': '52 x 44 x 18 cm',
      'Chassis': 'Aero-grade Magnesium'
    },
    colors: ['Onyx Black', 'Stone Grey', 'Sage Green'],
    createdAt: '2026-01-14'
  },

  // Additional rich products across all categories
  {
    id: 'prod-ergonomic-chair',
    name: 'Nordic Oak & Linen Minimalist Armchair',
    category: 'Home & Living',
    price: 15500,
    originalPrice: 21000,
    discountPercent: 26,
    rating: 4.9,
    reviewCount: 145,
    imageUrl: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&auto=format&fit=crop&q=80',
    sellerId: 'seller-2',
    sellerName: 'Casa Living Objects',
    sellerRating: 4.8,
    sellerLocation: 'Austin, TX',
    isNewArrival: true,
    inStock: true,
    stockCount: 14,
    isActive: false,
    description: 'Sculptural lounge chair featuring solid white oak legs and breathable high-density Belgian linen weave upholstery.',
    features: ['Solid FSC-certified White Oak', 'Stain-resistant linen treatment', 'High-resilience memory foam core'],
    specifications: { 'Seat Height': '42cm', 'Width': '68cm', 'Max Weight': '150kg' },
    createdAt: '2026-02-28'
  },
  {
    id: 'prod-ceramic-chemex',
    name: 'Matte Stoneware Pour-Over Dripper & Mug',
    category: 'Home & Living',
    price: 1650,
    originalPrice: 2350,
    discountPercent: 30,
    rating: 4.8,
    reviewCount: 220,
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
    sellerId: 'seller-2',
    sellerName: 'Casa Living Objects',
    sellerRating: 4.8,
    sellerLocation: 'Austin, TX',
    inStock: true,
    stockCount: 45,
    isActive: false,
    description: 'Hand-thrown stoneware brewer with spiral internal ridges for steady brew times and exceptional clarity.',
    features: ['High-fired durable ceramic', 'Dishwasher & microwave safe', 'Fits standard #02 cone filters'],
    specifications: { 'Capacity': '450ml', 'Weight': '400g' },
    createdAt: '2026-02-10'
  },
  {
    id: 'prod-leather-boots',
    name: 'Full-Grain Handcrafted Chelsea Boots',
    category: 'Fashion',
    price: 4800,
    originalPrice: 7200,
    discountPercent: 33,
    rating: 4.9,
    reviewCount: 380,
    imageUrl: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=600&auto=format&fit=crop&q=80',
    sellerId: 'seller-1',
    sellerName: 'Urban Thread Studio',
    sellerRating: 4.9,
    sellerLocation: 'Portland, OR',
    isNewArrival: true,
    inStock: true,
    stockCount: 2,
    isActive: false,
    description: 'Constructed from vegetable-tanned Italian pull-up leather with Goodyear welted rubber lug outsoles.',
    features: ['Goodyear welted re-soleable construction', 'Soft calfskin lining', 'Elastic side gussets for slip-on ease'],
    specifications: { 'Upper': '100% Full Grain Leather', 'Sole': 'Vibram Commando Rubber' },
    colors: ['Cognac Brown', 'Matte Black'],
    sizes: ['8', '9', '10', '11', '12'],
    createdAt: '2026-02-22'
  },
  {
    id: 'prod-linen-shirt',
    name: 'Relaxed Pure Linen Camp Collar Shirt',
    category: 'Fashion',
    price: 2100,
    originalPrice: 3000,
    discountPercent: 30,
    rating: 4.8,
    reviewCount: 195,
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&auto=format&fit=crop&q=80',
    sellerId: 'seller-1',
    sellerName: 'Urban Thread Studio',
    sellerRating: 4.9,
    sellerLocation: 'Portland, OR',
    inStock: true,
    stockCount: 52,
    isActive: false,
    description: 'Pre-washed French flax linen shirt with an open camp collar, pearl buttons, and straight boxy hem.',
    features: ['100% European Flax linen', 'Natural shell buttons', 'Breathable natural temperature regulation'],
    specifications: { 'Weave': '170 GSM Washed Linen', 'Origin': 'Portugal' },
    colors: ['Crisp White', 'Natural Flax', 'Sage Green'],
    sizes: ['S', 'M', 'L', 'XL'],
    createdAt: '2026-01-30'
  },
  {
    id: 'prod-wooden-stacker',
    name: 'Montessori Rainbow Arch Wooden Toy Set',
    category: 'Baby & Kids',
    price: 1250,
    originalPrice: 1800,
    discountPercent: 31,
    rating: 4.9,
    reviewCount: 280,
    imageUrl: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=600&auto=format&fit=crop&q=80',
    sellerId: 'seller-6',
    sellerName: 'Little Sprout Studio',
    sellerRating: 4.9,
    sellerLocation: 'Boulder, CO',
    inStock: true,
    stockCount: 35,
    isActive: false,
    description: 'Seven nested solid linden wood stacking arches finished in food-safe non-toxic natural water-based stains.',
    features: ['Fosters spatial thinking & motor coordination', 'Velvety unvarnished non-slip grip', 'Sustainably sourced German Beech'],
    specifications: { 'Pieces': '7 nesting arches', 'Dimensions': '26 x 13 x 5 cm' },
    createdAt: '2026-02-08'
  },
  {
    id: 'prod-dumbbells-hex',
    name: 'Cast Iron Hex Dumbbells (Pair, 15 lbs)',
    category: 'Sports',
    price: 3400,
    originalPrice: 4900,
    discountPercent: 31,
    rating: 4.9,
    reviewCount: 310,
    imageUrl: 'https://images.unsplash.com/photo-1586401100295-7a8096fd231a?w=600&auto=format&fit=crop&q=80',
    sellerId: 'seller-3',
    sellerName: 'TechNest Labs',
    sellerRating: 4.9,
    sellerLocation: 'San Jose, CA',
    inStock: true,
    stockCount: 40,
    isActive: false,
    description: 'Heavy-duty solid iron dumbbells encased in virgin rubber coating to protect home floors and minimize clatter.',
    features: ['Anti-roll hexagonal head design', 'Ergonomic knurled chrome steel handle', 'Shock-absorbing protective rubber'],
    specifications: { 'Weight': '2 x 15 lbs (30 lbs total)', 'Handle Diameter': '28mm' },
    createdAt: '2026-01-12'
  },
  {
    id: 'prod-yoga-mat',
    name: 'Natural Tree Rubber Non-Slip Yoga Mat (5mm)',
    category: 'Sports',
    price: 2200,
    originalPrice: 3200,
    discountPercent: 31,
    rating: 4.8,
    reviewCount: 245,
    imageUrl: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&auto=format&fit=crop&q=80',
    sellerId: 'seller-3',
    sellerName: 'TechNest Labs',
    sellerRating: 4.9,
    sellerLocation: 'San Jose, CA',
    inStock: true,
    stockCount: 65,
    isActive: false,
    description: 'Eco-conscious dense rubber base topped with laser-etched alignment guides. Wet-grip technology gets tackier with sweat.',
    features: ['Zero PVC, toxic glues or heavy metals', 'Optimal 5mm joint cushioning', 'Complimentary carrying strap included'],
    specifications: { 'Length': '183cm x 68cm', 'Thickness': '5mm', 'Weight': '2.4kg' },
    colors: ['Moss Green', 'Slate Ash', 'Deep Plum'],
    createdAt: '2026-02-14'
  },
  {
    id: 'prod-artisan-coffee-beans',
    name: 'Ethiopian Yirgacheffe Single-Origin Roast (12 oz)',
    category: 'Groceries',
    price: 950,
    originalPrice: 1250,
    discountPercent: 24,
    rating: 4.9,
    reviewCount: 410,
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&auto=format&fit=crop&q=80',
    sellerId: 'seller-5',
    sellerName: 'Daily Harvest Provisions',
    sellerRating: 4.8,
    sellerLocation: 'Seattle, WA',
    isNewArrival: true,
    inStock: true,
    stockCount: 90,
    isActive: false,
    description: 'Washed heirloom beans roasted in small batches. Notes of bergamot, candied jasmine flowers, and crisp peach.',
    features: ['Grade 1 Specialty Arabica', 'Roasted fresh within 48 hours of shipment', 'Nitrogen-flushed valve bag'],
    specifications: { 'Process': 'Washed', 'Altitude': '1,950m - 2,200m', 'Roast': 'Light-Medium' },
    createdAt: '2026-03-01'
  },
  {
    id: 'prod-wildflower-honey',
    name: 'Raw Unfiltered Mountain Wildflower Honey',
    category: 'Groceries',
    price: 750,
    originalPrice: 950,
    discountPercent: 21,
    rating: 4.9,
    reviewCount: 185,
    imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&auto=format&fit=crop&q=80',
    sellerId: 'seller-5',
    sellerName: 'Daily Harvest Provisions',
    sellerRating: 4.8,
    sellerLocation: 'Seattle, WA',
    inStock: true,
    stockCount: 75,
    isActive: false,
    description: 'Cold-extracted raw honey preserving active enzymes and wildflower pollen from Pacific Northwest alpine meadows.',
    features: ['Never heated above hive temperature', 'Single source apiary', 'Zero additives or syrups'],
    specifications: { 'Size': '16 oz (454g) Glass Jar', 'Country': 'USA' },
    createdAt: '2026-02-19'
  },
  {
    id: 'prod-design-monograph',
    name: 'The Architecture of Simplicity (Hardcover)',
    category: 'Books',
    price: 1850,
    originalPrice: 2600,
    discountPercent: 29,
    rating: 4.9,
    reviewCount: 160,
    imageUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80',
    sellerId: 'seller-1',
    sellerName: 'Urban Thread Studio',
    sellerRating: 4.9,
    sellerLocation: 'Portland, OR',
    inStock: true,
    stockCount: 30,
    isActive: false,
    description: 'A sumptuous 280-page exploration of Japanese joinery, Scandinavian interiors, and contemporary minimalist living.',
    features: ['Clothbound linen hardcover with debossed foil', 'Over 200 full-bleed architectural photographs', 'FSC-certified heavyweight matte paper'],
    specifications: { 'Pages': '288 Pages', 'Format': 'Hardcover Cloth', 'Dimensions': '24 x 31 cm' },
    createdAt: '2026-01-28'
  },
  {
    id: 'prod-minimalist-watch-analog',
    name: 'Kanso Minimalist Bauhaus Watch',
    category: 'Electronics',
    price: 4200,
    originalPrice: 5900,
    discountPercent: 29,
    rating: 4.8,
    reviewCount: 310,
    imageUrl: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600&auto=format&fit=crop&q=80',
    sellerId: 'seller-3',
    sellerName: 'TechNest Labs',
    sellerRating: 4.9,
    sellerLocation: 'San Jose, CA',
    inStock: true,
    stockCount: 42,
    isActive: false,
    description: 'Ultra-slim 38mm brushed stainless steel casing powered by a Japanese Miyota quartz movement and vegetable-tanned leather strap.',
    features: ['316L Surgical Grade Stainless Steel', 'Sapphire coated scratchproof crystal', 'Water resistant to 30 meters'],
    specifications: { 'Case Diameter': '38mm', 'Thickness': '7.2mm', 'Movement': 'Japanese Quartz' },
    colors: ['Rose Gold / Tan', 'Silver / Black', 'Gunmetal / Grey'],
    createdAt: '2026-02-04'
  },
  {
    id: 'prod-sunscreen-drops',
    name: 'Mineral Tinted Daily Sun Drops SPF 50',
    category: 'Beauty',
    price: 1200,
    originalPrice: 1750,
    discountPercent: 31,
    rating: 4.9,
    reviewCount: 540,
    imageUrl: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&auto=format&fit=crop&q=80',
    sellerId: 'seller-4',
    sellerName: 'Glow & Co. Botanicals',
    sellerRating: 4.9,
    sellerLocation: 'Santa Barbara, CA',
    isDeal: true,
    inStock: true,
    stockCount: 88,
    isActive: false,
    description: 'Weightless 100% zinc oxide liquid broad-spectrum sunscreen that disappears into skin without white cast, delivering a radiant dewy glow.',
    features: ['Non-nano zinc oxide protection', 'Reef-friendly & water-resistant 40 mins', 'Enriched with Niacinamide & Aloe'],
    specifications: { 'Volume': '50ml', 'Broad Spectrum': 'UVA / UVB SPF 50' },
    createdAt: '2026-02-24'
  }
];

export const DEMO_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-earbuds-pro',
    author: 'Elena Rostova',
    rating: 5,
    date: 'March 14, 2026',
    title: 'Sound stage is unmatched at this price point',
    comment: 'The active noise cancellation completely isolates me on my daily commute. Bass is deep without muddying vocals. Fast shipping from TechNest Labs!',
    verifiedPurchase: true,
    orderNumber: 'ZI-8942',
    helpfulCount: 24,
    recommended: true
  },
  {
    id: 'rev-2',
    productId: 'prod-earbuds-pro',
    author: 'Marcus Vance',
    rating: 5,
    date: 'March 8, 2026',
    title: 'Compact case and pristine battery life',
    comment: 'I only need to charge the capsule once a week. Microphone clarity for Zoom calls is crystal clear and pairing with my laptop is instant.',
    verifiedPurchase: true,
    orderNumber: 'ZI-8942',
    helpfulCount: 16,
    recommended: true
  },
  {
    id: 'rev-3',
    productId: 'prod-minimalist-backpack',
    author: 'Julian Thorne',
    rating: 5,
    date: 'March 2, 2026',
    title: 'Exceptional weather protection and fit',
    comment: 'Wore this jacket in heavy rain and stayed completely dry. The taped seams and breathable lining feel premium and comfortable.',
    verifiedPurchase: true,
    orderNumber: 'ZI-7419',
    helpfulCount: 31,
    recommended: true
  },
  {
    id: 'rev-4',
    productId: 'prod-scented-candle',
    author: 'Sarah Jenkins',
    rating: 5,
    date: 'February 27, 2026',
    title: 'Subtle and grounding cedar scent',
    comment: 'Fills my living room with a warm cedar and amber scent that is neither overwhelming nor synthetic. The matte ceramic vessel is stunning.',
    verifiedPurchase: true,
    orderNumber: 'ZI-8942',
    helpfulCount: 12,
    recommended: true
  },
  {
    id: 'rev-5',
    productId: 'prod-smartwatch',
    author: 'David Chen',
    rating: 5,
    date: 'March 18, 2026',
    title: 'Flawless AMOLED screen and sapphire glass',
    comment: 'Battery lasts a full 7 days with always-on display turned on. Sleep tracking matches my hospital pulse oximeter accurately.',
    verifiedPurchase: true,
    orderNumber: 'ZI-5520',
    helpfulCount: 19,
    recommended: true
  },
  {
    id: 'rev-6',
    productId: 'prod-skincare-set',
    author: 'Amara Patel',
    rating: 5,
    date: 'March 11, 2026',
    title: 'Transformed my dry seasonal skin',
    comment: 'The rosehip elixir absorbs completely without any greasy residue. My skin barrier feels restored and glowing after just 10 days of use.',
    verifiedPurchase: true,
    orderNumber: 'ZI-6204',
    helpfulCount: 28,
    recommended: true
  },
  {
    id: 'rev-7',
    productId: 'prod-linen-shirt',
    author: 'Benjamin Lee',
    rating: 4,
    date: 'March 5, 2026',
    title: 'Breathable linen, true to European sizing',
    comment: 'High quality French flax with reinforced mother-of-pearl buttons. Fits tailored around the shoulders and softens even more after the second wash.',
    verifiedPurchase: true,
    orderNumber: 'ZI-3199',
    helpfulCount: 9,
    recommended: true
  }
];

export const DEMO_ORDERS: Order[] = [
  {
    id: 'ord-1',
    orderNumber: 'ZI-8942',
    customerId: 'cust-101',
    customerName: 'Alex Mercer',
    customerEmail: 'alex.mercer@example.com',
    items: [
      {
        productId: 'prod-earbuds-pro',
        productName: 'Wireless Earbuds Pro with Spatial Audio',
        imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80',
        sellerId: 'seller-3',
        sellerName: 'TechNest Labs',
        price: 2499,
        quantity: 1
      },
      {
        productId: 'prod-scented-candle',
        productName: 'Artisan Sandalwood & Cedar Scented Candle',
        imageUrl: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&auto=format&fit=crop&q=80',
        sellerId: 'seller-2',
        sellerName: 'Casa Living Objects',
        price: 850,
        quantity: 2
      }
    ],
    subOrders: [
      {
        id: 'sub-ord-1-A',
        subOrderNumber: 'ZI-8942-A',
        parentOrderId: 'ord-1',
        sellerId: 'seller-3',
        sellerName: 'TechNest Labs',
        items: [
          {
            productId: 'prod-earbuds-pro',
            productName: 'Wireless Earbuds Pro with Spatial Audio',
            imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80',
            sellerId: 'seller-3',
            sellerName: 'TechNest Labs',
            price: 2499,
            quantity: 1,
            subtotal: 2499
          }
        ],
        subtotal: 2499,
        shippingFee: 0,
        commissionRate: 8.0,
        commissionAmount: 200,
        sellerEarnings: 2299,
        status: 'Shipped',
        trackingNumber: 'TRK-TECH-9812',
        estimatedDelivery: 'March 24, 2026',
        carrier: 'Zero Invest Express'
      },
      {
        id: 'sub-ord-1-B',
        subOrderNumber: 'ZI-8942-B',
        parentOrderId: 'ord-1',
        sellerId: 'seller-2',
        sellerName: 'Casa Living Objects',
        items: [
          {
            productId: 'prod-scented-candle',
            productName: 'Artisan Sandalwood & Cedar Scented Candle',
            imageUrl: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&auto=format&fit=crop&q=80',
            sellerId: 'seller-2',
            sellerName: 'Casa Living Objects',
            price: 850,
            quantity: 2,
            subtotal: 1700
          }
        ],
        subtotal: 1700,
        shippingFee: 0,
        commissionRate: 7.5,
        commissionAmount: 128,
        sellerEarnings: 1572,
        status: 'Delivered',
        trackingNumber: 'TRK-CASA-4410',
        estimatedDelivery: 'March 22, 2026',
        carrier: 'Casa Ground Courier'
      }
    ],
    subtotal: 4199,
    shipping: 0,
    discount: 200,
    total: 3999,
    status: 'Shipped',
    createdAt: '2026-03-18',
    shippingAddress: {
      fullName: 'Alex Mercer',
      street: '742 Evergreen Terrace',
      city: 'Dhaka',
      state: 'Dhaka',
      zipCode: '1212',
      country: 'Bangladesh',
      phone: '+880 1712-345678'
    },
    paymentMethod: 'card',
    trackingNumber: 'TRK-9812-4410',
    estimatedDelivery: 'March 24, 2026'
  },
  {
    id: 'ord-2',
    orderNumber: 'ZI-7419',
    customerId: 'cust-101',
    customerName: 'Alex Mercer',
    customerEmail: 'alex.mercer@example.com',
    items: [
      {
        productId: 'prod-minimalist-backpack',
        productName: 'Minimalist Weatherproof Jacket',
        imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80',
        sellerId: 'seller-1',
        sellerName: 'Urban Thread Studio',
        price: 3200,
        quantity: 1
      }
    ],
    subtotal: 3200,
    shipping: 100,
    discount: 0,
    total: 3300,
    status: 'Delivered',
    createdAt: '2026-02-28',
    shippingAddress: {
      fullName: 'Alex Mercer',
      street: '742 Evergreen Terrace',
      city: 'Dhaka',
      state: 'Dhaka',
      zipCode: '1212',
      country: 'Bangladesh',
      phone: '+880 1712-345678'
    },
    paymentMethod: 'card',
    trackingNumber: 'TRK-6731-8902',
    estimatedDelivery: 'March 3, 2026'
  }
];

export const DEMO_COUPONS: Coupon[] = [
  { code: 'ZEROINVEST10', discountPercent: 10, minPurchase: 1500, description: '10% off on orders over ৳1,500' },
  { code: 'FREESHIP', discountPercent: 5, minPurchase: 1000, description: '৳100 shipping rebate' },
  { code: 'WELCOME20', discountPercent: 20, minPurchase: 2500, description: '20% off for first-time marketplace customers' }
];

